-- MySQL Script generated by MySQL Workbench
-- Tue Jan 30 22:57:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DWARFS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DWARFS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DWARFS` DEFAULT CHARACTER SET utf8 ;
USE `DWARFS` ;

-- -----------------------------------------------------
-- Table `DWARFS`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`users` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `first_name` VARCHAR(64) CHARACTER SET 'utf8mb4' NOT NULL,
  `last_name` VARCHAR(64) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userid_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`chats` (
  `chat_id` BIGINT(20) NOT NULL,
  `chat_name` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL,
  PRIMARY KEY (`chat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`rules` (
  `rule_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(2048) NOT NULL,
  `load_id` INT UNSIGNED NOT NULL,
  `chat_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`rule_id`),
  INDEX `groupid_idx` (`chat_id` ASC) VISIBLE,
  UNIQUE INDEX `rule_group_id_UNIQUE` (`chat_id` ASC) VISIBLE,
  UNIQUE INDEX `rules_id_UNIQUE` (`rule_id` ASC) VISIBLE,
  CONSTRAINT `rule_chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `DWARFS`.`chats` (`chat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`states` (
  `mute` DATETIME NULL,
  `ban` DATETIME NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `chat_id` BIGINT(20) NOT NULL,
  `rule_id` BIGINT(20) UNSIGNED NOT NULL,
  `date_add_user_to_group` DATETIME NOT NULL,
  INDEX `groupid_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `state_chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `DWARFS`.`chats` (`chat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `state_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DWARFS`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `state_rule_id`
    FOREIGN KEY (`rule_id`)
    REFERENCES `DWARFS`.`rules` (`rule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`achives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`achives` (
  `achive_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `achive_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`achive_id`),
  UNIQUE INDEX `id_UNIQUE` (`achive_id` ASC) VISIBLE,
  UNIQUE INDEX `achive_UNIQUE` (`achive_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`messages` (
  `time` INT NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `chat_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `message_user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `message_group_id_UNIQUE` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `message_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DWARFS`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `message_chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `DWARFS`.`chats` (`chat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`progreses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`progreses` (
  `progres` INT(2) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `achive_id` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `progres_user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `progres_achive_id_UNIQUE` (`achive_id` ASC) VISIBLE,
  CONSTRAINT `progres_achive_id`
    FOREIGN KEY (`achive_id`)
    REFERENCES `DWARFS`.`achives` (`achive_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `progres_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DWARFS`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`custom_commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`custom_commands` (
  `command_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comm_name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `need_target` TINYINT(1) NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`command_id`),
  UNIQUE INDEX `custom_commands_id_UNIQUE` (`command_id` ASC) VISIBLE,
  UNIQUE INDEX `custom_user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `custom_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DWARFS`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DWARFS`.`marriages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DWARFS`.`marriages` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `chat_id` BIGINT(20) NOT NULL,
  `date` DATE NOT NULL,
  INDEX `marriages_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `marriages_group_id_idx` (`chat_id` ASC) VISIBLE,
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE,
  CONSTRAINT `marriages_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DWARFS`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `marriages_chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `DWARFS`.`chats` (`chat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
